"""Remove Razorpay, Use UPI

Revision ID: 32aceec8049c
Revises: a3a672851515
Create Date: 2026-03-20 05:44:51.187341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aceec8049c'
down_revision = 'a3a672851515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('razorpay_transfer_id')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('razorpay_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_account_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('razorpay_transfer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
