"""Added condition, genre, handoff_location to Book

Revision ID: 76ae0778bf5f
Revises: f81eaad010b3
Create Date: 2026-04-09 23:28:29.167541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ae0778bf5f'
down_revision = 'f81eaad010b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('handoff_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('handoff_location')
        batch_op.drop_column('genre')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
