"""Remove complex subsystems

Revision ID: d1fe52a412db
Revises: 32aceec8049c
Create Date: 2026-04-02 21:22:19.058341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1fe52a412db'
down_revision = '32aceec8049c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('cart_items')
    op.drop_table('notifications')
    op.drop_table('proposals')
    op.drop_table('borrow_records')
    op.drop_table('transactions')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('upi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('transactions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tx_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('upi_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('buyer_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seller_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='transactions_book_id_fkey'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='transactions_buyer_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='transactions_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('borrow_records',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('borrow_records_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('returned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('late_fee_accrued', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='borrow_records_book_id_fkey'),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], name='borrow_records_borrower_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='borrow_records_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='borrow_records_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('proposals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('target_book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offered_book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offered_cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['offered_book_id'], ['books.id'], name=op.f('proposals_offered_book_id_fkey')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('proposals_owner_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('proposals_requester_id_fkey')),
    sa.ForeignKeyConstraint(['target_book_id'], ['books.id'], name=op.f('proposals_target_book_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proposals_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ref_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ref_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actionable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('cart_items_book_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cart_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey'))
    )
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('borrow_record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['borrow_record_id'], ['borrow_records.id'], name=op.f('ratings_borrow_record_id_fkey')),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], name=op.f('ratings_reviewee_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('ratings_reviewer_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('ratings_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ratings_pkey'))
    )
    # ### end Alembic commands ###
