"""Add cascade delete to books

Revision ID: f81eaad010b3
Revises: 3ba9871b8470
Create Date: 2026-04-04 19:22:17.727195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81eaad010b3'
down_revision = '3ba9871b8470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('books_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('books_owner_id_fkey'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###
